Add a missing OpenSSL dependency on Unix: dl (#623).
Without it, RetDec fails to build on some systems, e.g. via our Dockerfile that
is based on Ubuntu Bionic and does not (at the time of writing) use a pre-built
version of OpenSSL:

    ../../deps/openssl/openssl/src/openssl-install/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
    dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
    dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
    dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'