Fix the build of bin2llvmirtool after the added support for macOS build (#62).
In 55c2d04202c70f4d9d27ca27bb146d7d4066d9f8, support for macOS build was added.
It applied the following patch (note the last line):

    -else() # Linux/MSYS2
    +elseif(APPLE)
    +   target_link_libraries(bin2llvmirtool -Wl,-force_load bin2llvmir)
    +elseif() # Linux/MSYS2

The last `elseif()` should have been `else()`. This caused any Linux build to
fail with the following error because of the missing dependency on bin2llvmir:

    bin2llvmir.cpp:18:10: fatal error: llvm/ADT/Triple.h: No such file or directory